### ISSUE TITLE
this is not how to use Github

### ISSUE THREAD

**Issue by Geolykt** [Ryanisthere/Suicidebombingplugin#1]
Github has the intend of versioning the source (through commits or other ways), not to version the releases. Although you can do that, the release tab is suited better, where as the rest can be used for Issue/bug/feature tracking as well as to add informational content (like README.MD or LICENSE). The ideal use of github (and any other source versioning plattform) is to be able to read the source and to contribute to it, which allows to make Open-Source content.

Thanks for you understanding

**Comment by Ryanisthere** [comment]
> Github has the intend of versioning the source (through commits or other ways), not to version the releases. Although you can do that, the release tab is suited better, where as the rest can be used for Issue/bug/feature tracking as well as to add informational content (like README.MD or LICENSE). The ideal use of github (and any other source versioning plattform) is to be able to read the source and to contribute to it, which allows to make Open-Source content.
> 
> Thanks for you understanding

Sorry i am very new to this 
this is my first time trying to use github

**Comment by rautamiekka** [comment]
Yes, the wrong way to use a version control system.

Alternatively you can make the repo private but still keep your source on GitHub.

Private repos for Game Server plugins are a dick move, though, and being Java the decompilation ain't anything rocket science.

Git is pretty stupidly hard to use, though, and GitHub doesn't make it any easier.
